books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.BookListView.as_view(), name='book-list'),
    path('detail/<uuid:pk>/', views.BookDetailView.as_view(),
         name='book-detail'),
    path('update/<uuid:pk>/', views.BookUpdateView.as_view(),
         name='book-update'),
    path('delete/<uuid:pk>/', views.BookDeleteView.as_view(),
         name='book-delete'),
    path('create/', views.BookCreateView.as_view(), name='book-create'),
]

bookshelves/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
]

books/models.py
import uuid

from django.db import models

from departments.models import Department


class Book(models.Model):
    """書籍モデルクラス"""
    id = models.UUIDField('ID', primary_key=True, default=uuid.uuid4)
    name = models.CharField('書籍名', max_length=100)
    publisher = models.CharField('出版社', max_length=100, null=True,
                                 blank=True)
    isbn = models.CharField('ISBN', max_length=30, null=True, blank=True)
    published_at = models.DateField('発売日', null=True, blank=True)
    price = models.IntegerField('税抜き価格')
    department = models.ForeignKey(Department, db_column='部署ID',
                                   on_delete=models.CASCADE,
                                   verbose_name='部署')
    registered_at = models.DateTimeField('更新日時', auto_now_add=True)
    updated_at = models.DateTimeField('更新日時', auto_now=True)

    def __str__(self) -> str:
        """書籍名を返却する。

        Returns:
            書籍名。
        """
        return self.name

    class Meta:
        db_table = 'books'  # データベーステーブル名。
        verbose_name = verbose_name_plural = '書籍'

departments/models.py
from django.db import models


class Department(models.Model):
    """部署モデルクラス"""
    name = models.CharField('部署名', max_length=80)

    class Meta:
        verbose_name = verbose_name_plural = '部署'
        ordering = ('id',)

    def __str__(self) -> str:
        """部署名を返却する。

        Returns:
            部署名。
        """
        return self.name

books/views.py
from typing import Dict, Type

from django.urls import reverse, reverse_lazy
from django import forms
from django.views import generic

from .models import Book


class BookCreateView(generic.CreateView):
    """書籍登録ビュー"""
    model = Book
    fields = ('id', 'name', 'publisher', 'isbn', 'published_at', 'price',
              'department',)

    def get_form(self, form_class: Type[forms.Form] = None) -> forms.Form:
        """書籍登録ビューのフォームを返却する。

        Args:
            form_class: フォームクラス。
        Returns:
            書籍登録ビューのフォーム。
        """
        form = super().get_form(form_class)
        form.fields['id'].widget = forms.HiddenInput()  # 隠されたフィールドに設定
        form.fields['department'].empty_label = None  # 未入力項目を非表
        return form

    def get_context_data(self, **kwargs: Dict) -> Dict:
        """テンプレートをレンダリングするときに使用するデータを格納した辞書を返却する。

        Args:
            **kwargs: コンテキストに登録するデータを格納した辞書。
        Returns:
            テンプレートをレンダリングするときに使用するデータを格納した辞書。
        """
        ctx = super().get_context_data(**kwargs)
        ctx['submit_name'] = 'register'
        ctx['submit_value'] = '登録'
        return ctx

    def get_success_url(self) -> str:
        """書籍登録後に遷移するページのURIを返却する。

        Returns:
            書籍登録後に遷移するページのURI。
        """
        return reverse('books:book-detail', kwargs={'pk': self.object.id})


class BookListView(generic.ListView):
    """書籍リストビュー"""
    model = Book


class BookDetailView(generic.DetailView):
    """書籍詳細ビュー"""
    model = Book


class BookUpdateView(generic.UpdateView):
    """書籍更新ビュー"""
    model = Book
    fields = ('name', 'publisher', 'isbn', 'published_at', 'price',
              'department',)

    def get_form(self, form_class=None) -> forms.Form:
        """書籍登録ビューのフォームを返却する。

        Args:
            form_class: フォームクラス。
        Returns:
            書籍登録ビューのフォーム。
        """
        form = super().get_form(form_class)
        form.fields['department'].empty_label = None  # 未入力項目を非表示
        return form

    def get_context_data(self, **kwargs: Dict) -> Dict:
        """テンプレートをレンダリングするときに使用するデータを格納した辞書を
           返却する。

        Args:
            **kwargs: コンテキストに登録するデータを格納した辞書。
        Returns:
            テンプレートをレンダリングするときに使用するデータを格納した辞書。
        """
        ctx = super().get_context_data(**kwargs)
        ctx['submit_name'] = 'update'
        ctx['submit_value'] = '更新'
        return ctx

    def get_success_url(self) -> str:
        """書籍更新後に遷移するページのURIを返却する。

        Returns:
            書籍更新後に遷移するページのURI。
        """
        return reverse('books:book-detail', kwargs={'pk': self.object.id})


class BookDeleteView(generic.DeleteView):
    """書籍削除ビュー"""
    model = Book
    success_url = reverse_lazy('books:book-list')

books/templates/books/book_confirm_delete.html
<html lang="ja">
<head>
  <meta charset="utf-8">
</head>
<body>
  <!-- ブレットクラム-->
  <div>
    <a href="{% url 'books:book-list' %}">書籍リスト</a> |  書籍削除
  </div>
  <!-- タイトル -->
  <h1>書籍の削除</h1>
  <!-- 書籍の属性 -->
  <p><label>書籍名:</label> {{ object.name }}</p>
  <p><label>出版社:</label> {{ object.publisher }}</p>
  <p><label>ISBN:</label> {{ object.isbn }}</p>
  <p><label>発売日:</label> {{ object.published_at }}</p>
  <p><label>税抜き価格:</label> {{ object.price }}</p>
  <p><label>部署:</label> {{ object.department }}</p>
  <p><label>登録日時:</label> {{ object.registered_at }}</p>
  <p><label>更新日時:</label> {{ object.updated_at }}</p>
  <form method="post">
    {% csrf_token %}
    <p>この書籍を削除しますか?</p>
    <input type="submit" value="削除">
  </form>
</body>
</html>

books/templates/books/book_detail.html
<html lang="ja">
<head>
  <meta charset="utf-8">
</head>
<body>
  <!-- ブレットクラム-->
  <div>
    <a href="{% url 'books:book-list' %}">書籍リスト</a> |  書籍詳細
  </div>
  <!-- タイトル -->
  <h1>書籍の詳細</h1>
  <!-- 書籍の属性 -->
  <p><label>書籍名:</label> {{ object.name }}</p>
  <p><label>出版社:</label> {{ object.publisher }}</p>
  <p><label>ISBN:</label> {{ object.isbn }}</p>
  <p><label>発売日:</label> {{ object.published_at }}</p>
  <p><label>税抜き価格:</label> {{ object.price }}</p>
  <p><label>部署:</label> {{ object.department }}</p>
  <p><label>登録日時:</label> {{ object.registered_at }}</p>
  <p><label>更新日時:</label> {{ object.updated_at }}</p>
  <a href="{% url 'books:book-update' object.id %}">更新</a>
</body>
</html>

books/templates/books/book_form.html
<html lang="ja">
<head>
  <meta charset="utf-8">
</head>
<body>
  <!-- ブレットクラム-->
  <div>
    <a href="{% url 'books:book-list' %}">書籍リスト</a> |  書籍{{ submit_value }}
  </div>
  <!-- タイトル -->
  <h1>書籍の{{ submit_value }}</h1>
  <!-- フォーム -->
  <form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p }}
    <input type="submit" name="{{ submit_name }}" value="{{ submit_value }}">
  </form>
</body>
</html>

books/templates/books/book_list.html
<html lang="ja">
<head>
  <meta charset="utf-8">
</head>
<body>
  <!-- ブレットクラム -->
  <div>書籍リスト</div>
  <!-- タイトル-->
  <h1>書籍の一覧</h1>
  <!-- 書籍リストテーブル -->
  <table border="1">
    <thead>
      <tr>
        <th>書籍名</th>
        <th>出版社</th>
        <th>ISBN</th>
        <th>発売日</th>
        <th>税抜き価格</th>
        <th>部署</th>
        <th />
        <th />
      </tr>
    </thead>
    <tbody>
      {% for book in object_list %}
      <tr>
        <td>{{ book.name }}</td>
        <td>{{ book.publisher }}</td>
        <td>{{ book.isbn }}</td>
        <td>{{ book.published_at }}</td>
        <td>{{ book.price }}</td>
        <td>{{ book.department }}</td>
        <td><a href="{% url 'books:book-detail' book.id %}">詳細</a></td>
        <td><a href="{% url 'books:book-delete' book.id %}">削除</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'books:book-create' %}">登録</a>
</body>
</html>